"""Add binary file storage

Revision ID: 08466f23b97e
Revises: fcecc36458bf
Create Date: 2025-05-07 10:08:12.866273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08466f23b97e'
down_revision = 'fcecc36458bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduation_certificate_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('graduation_certificate_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('graduation_certificate_mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_certificate_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('birth_certificate_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('birth_certificate_mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('family_card_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('family_card_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('family_card_mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('report_card_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('report_card_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('report_card_mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo_mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('track_document_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('track_document_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('track_document_mimetype', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('track_document_mimetype')
        batch_op.drop_column('track_document_filename')
        batch_op.drop_column('track_document_data')
        batch_op.drop_column('photo_mimetype')
        batch_op.drop_column('photo_filename')
        batch_op.drop_column('photo_data')
        batch_op.drop_column('report_card_mimetype')
        batch_op.drop_column('report_card_filename')
        batch_op.drop_column('report_card_data')
        batch_op.drop_column('family_card_mimetype')
        batch_op.drop_column('family_card_filename')
        batch_op.drop_column('family_card_data')
        batch_op.drop_column('birth_certificate_mimetype')
        batch_op.drop_column('birth_certificate_filename')
        batch_op.drop_column('birth_certificate_data')
        batch_op.drop_column('graduation_certificate_mimetype')
        batch_op.drop_column('graduation_certificate_filename')
        batch_op.drop_column('graduation_certificate_data')

    # ### end Alembic commands ###
