"""Add track documents

Revision ID: 0d93151a52e2
Revises: d1a3f45e204d
Create Date: 2025-05-08 11:07:49.601432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d93151a52e2'
down_revision = 'd1a3f45e204d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_docs_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('achievement_docs_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('achievement_docs_mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('affirmation_docs_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('affirmation_docs_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('affirmation_docs_mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('domicile_docs_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('domicile_docs_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('domicile_docs_mimetype', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('domicile_docs_mimetype')
        batch_op.drop_column('domicile_docs_filename')
        batch_op.drop_column('domicile_docs_data')
        batch_op.drop_column('affirmation_docs_mimetype')
        batch_op.drop_column('affirmation_docs_filename')
        batch_op.drop_column('affirmation_docs_data')
        batch_op.drop_column('achievement_docs_mimetype')
        batch_op.drop_column('achievement_docs_filename')
        batch_op.drop_column('achievement_docs_data')

    # ### end Alembic commands ###
