"""inilation

Revision ID: 274db2a983b0
Revises: f3264a985268
Create Date: 2025-05-22 10:02:58.774671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274db2a983b0'
down_revision = 'f3264a985268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_place', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('parent_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('previous_school', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('initial_form_submitted', sa.Boolean(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('initial_form_submitted')
        batch_op.drop_column('previous_school')
        batch_op.drop_column('parent_phone')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
