"""Add gender and religion fields

Revision ID: 43fd0d611d47
Revises: 0d93151a52e2
Create Date: 2025-05-14 10:34:36.651320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fd0d611d47'
down_revision = '0d93151a52e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('religion', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('religion')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
