"""Add document upload fields

Revision ID: fcecc36458bf
Revises: 10666509789f
Create Date: 2025-05-07 09:44:57.404655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcecc36458bf'
down_revision = '10666509789f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduation_certificate', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('birth_certificate', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('family_card', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('report_card', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('registration_track', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('track_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('file_metadata')
        batch_op.drop_column('track_document')
        batch_op.drop_column('registration_track')
        batch_op.drop_column('photo')
        batch_op.drop_column('report_card')
        batch_op.drop_column('family_card')
        batch_op.drop_column('birth_certificate')
        batch_op.drop_column('graduation_certificate')

    # ### end Alembic commands ###
